resolver: lts-21.25 # 9.4.8

packages:
- '.'

extra-deps:
- ConfigFile-1.1.4
- git: https://github.com/jacobpake/llvm-hs-12
  commit: a2554f70f2b2126f2b4586813dea2e4b48ef5aaf
  subdirs:
  - llvm-hs-pure
  - llvm-hs
- text-replace-0.1.0.3
- sbv-9.2
- syz-0.2.0.0
- git: https://github.com/jacobpake/granule
  commit: 739e37f353f86537f3ce318205c3769408cdf9b8
- git: https://github.com/jackohughes/haskell-src-exts
  commit: 5c2647fa0746bdac046897f5a6b7e4f5ef3afa79
- lsp-types-2.3.0.1
- lsp-2.7.0.1
- optparse-applicative-0.19.0.0
- criterion-1.6.4.1

allow-newer: true
allow-newer-deps:
- text-replace

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
